version: '3.9'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=10 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped